#ifndef THECHESS_MODEL_USER_CLASSIFICATION_HPP_
#define THECHESS_MODEL_USER_CLASSIFICATION_HPP_

namespace thechess {
namespace model {

enum Classification {
    SUPER_GRANDMASTER = 110,
    GRANDMASTER = 100,
    INTERNATIONAL_MASTER = 90,
    NATIONAL_MASTER = 80,
    EXPERT = 70,
    CLASSIFICATION_A = 50,
    CLASSIFICATION_B = 45,
    CLASSIFICATION_C = 40,
    CLASSIFICATION_D = 35,
    CLASSIFICATION_E = 30,
    CLASSIFICATION_F = 25,
    CLASSIFICATION_G = 20,
    CLASSIFICATION_H = 15,
    CLASSIFICATION_I = 10,
    CLASSIFICATION_J = 5,
    NO_CLASSIFICATION = 0
};

}
}

#endif
